[package]
name = "dbus_test"
version = "0.1.0"
authors = ["Vivek Kumar <vivek.kumar@axis.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libdbus-sys="*"
dbus="*"
